### ISSUE TITLE
config init NameError - MESSAGE_WRITE_DEFAULT is not defined

### ISSUE THREAD

**Issue by jar-b** [capitalone/giraffez#18]
`giraffez config --init` throws a NameError in 1.1.2:

```
Traceback (most recent call last):
  File "/home/ec2-user/.local/bin/giraffez", line 9, in <module>
    load_entry_point('giraffez==1.1.2', 'console_scripts', 'giraffez')()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/giraffez/__main__.py", line 25, in main
    MainCommand().run()
  File "/home/ec2-user/.local/lib/python2.7/site-packages/giraffez/core.py", line 91, in run
    args.run(args)
  File "/home/ec2-user/.local/lib/python2.7/site-packages/giraffez/commandline.py", line 147, in run
    log.write(MESSAGE_WRITE_DEFAULT.format(args.conf))
NameError: global name 'MESSAGE_WRITE_DEFAULT' is not defined
```

commandline.py (line 147) just needs to reference the new variable name from this commit b37054ed42b4683b05553e5fe67741339156eb4b:

From:
`log.write(MESSAGE_WRITE_DEFAULT.format(args.conf))`
To:
`log.write(message_write_default.format(args.conf))`

**Comment by ChrisRx** [comment]
Thanks for finding this one, don't know how it slipped through the cracks!  I can do this or if you submit a PR that works too, whichever you want.

**Comment by jar-b** [comment]
Sure, I can do a PR. Just wasn't sure what your preference was on versioning with such a small change.
