### ISSUE TITLE
Encrypting and pycryptodome

### ISSUE THREAD

**Issue by theianrobertson** [capitalone/giraffez#49]
I've been running into an issue in an environment where I have [pycryptodome](https://github.com/Legrandin/pycryptodome) installed (dependency of another package) when I try to encrypt passwords in `.girafferc`:

```
± giraffez config --init
colorful: true
connections:
  db1:
    host: null
    password: null
    username: null
  default: db1

Successfully created file '/Users/username/.girafferc'
Set the username and password using the config module:

    giraffez config --set connections.db1.host <host>
    giraffez config --set connections.db1.username <username>
    giraffez config --set connections.db1.password <password>
Key file '/Users/username/.giraffepg' created successfully.


± giraffez config --set connections.db1.password some_pass
Traceback (most recent call last):
  File "/Users/username/miniconda3/envs/env/bin/giraffez", line 11, in <module>
    sys.exit(main())
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/__main__.py", line 25, in main
    MainCommand().run()
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/core.py", line 80, in run
    args.run(args)
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/commandline.py", line 177, in run
    c.set_value(key, value)
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/config.py", line 298, in set_value
    value = self.encrypt(value, path)
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/config.py", line 171, in encrypt
    value = "ENCRYPTED:{}".format(ensure_str(self.cipher.encrypt(value)))
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/giraffez/encrypt.py", line 64, in encrypt
    return base64.b64encode(iv + cipher.encrypt(raw))
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/Crypto/Cipher/_mode_cbc.py", line 160, in encrypt
    expect_byte_string(plaintext)
  File "/Users/username/miniconda3/envs/env/lib/python3.6/site-packages/Crypto/Util/_raw_api.py", line 194, in expect_byte_string
    raise TypeError("Only byte strings can be passed to C code")
TypeError: Only byte strings can be passed to C code
```

I *think* that if we change [the line here](https://github.com/capitalone/giraffez/blob/master/giraffez/encrypt.py#L61) from `raw = self.pad(raw)` to `raw = self.pad(raw).encode("utf-8")` that would fix the issue.  In the `decrypt` function it's already assumed that the string is utf-8 encoded, so I don't think this would introduce any downstream issues.  That being said I've only done a little bit of testing.

From some reading it sounds like pycryptodome is more supported than pycrypto going forward, but I'm not familiar with the arguments there.

**Comment by ChrisRx** [comment]
I think `pycryptodome` (and probably `cryptography` as well) could be supported along with pycrypto.  I think that encoding here may cause problems for Python 2.7 style strings (where encoding is not implied by the data type and could be any number of things).  I think the safest thing to do here might be to change `giraffez.Crypto` and ensure that all code using it only gives bytes to the `encrypt/decrypt` methods.  Thoughts?
