### ISSUE TITLE
Giraffez compatibility with Python 3.7

### ISSUE THREAD

**Issue by flolas** [capitalone/giraffez#69]
Hi!
I'm testing Giraffez on Python 3.7 and have the following error:

```
Traceback (most recent call last):
  File "/Users/flolas/anaconda3/bin/giraffez", line 11, in <module>
    sys.exit(main())
  File "/Users/flolas/anaconda3/lib/python3.7/site-packages/giraffez/__main__.py", line 25, in main
    MainCommand().run()
  File "/Users/flolas/anaconda3/lib/python3.7/site-packages/giraffez/core.py", line 80, in run
    args.run(args)
  File "/Users/flolas/anaconda3/lib/python3.7/site-packages/giraffez/commandline.py", line 363, in run
    if FileReader.check_length(args.input_file, MLOAD_THRESHOLD):
  File "/Users/flolas/anaconda3/lib/python3.7/site-packages/giraffez/io.py", line 122, in check_length
    for i, line in enumerate(f, 1):
RuntimeError: generator raised StopIteration
```

This is when executing:

> giraffez insert com.csv PROD.CODES

**Comment by nickolasalvarado** [comment]
I am getting this same issue using a simple command like

`giraffez load "file.txt" "db.tablename"`
